title: GitHub/IBM POV Documents
description: Technical point of view documents for GitHub and IBM
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - Gemfile
  - Gemfile.lock
  - .github/
  - README.md
