title: GitHub/IBM POV Documents
description: Technical point of view documents for GitHub and IBM
theme: minima
baseurl: "/gi-pov"  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - "**/*.md"
exclude:
  - Gemfile
  - Gemfile.lock
  - .github/
  - README.md
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "gi-pov-2-assets"
      type: "pages"
    values:
      layout: "default"
      permalink: /:path/:basename:output_ext
