title: GitHub/IBM POV Documents
description: Technical point of view documents from IBM related to GitHub best practices
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - "**/*.md"
exclude:
  - Gemfile
  - Gemfile.lock
  - .github/
  - README.md
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "gi-pov-2-assets"
      type: "pages"
    values:
      layout: "default"
      permalink: /:path/:basename:output_ext
