name: Publish Markdown to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
    paths:
      - '**.md'  # Only trigger on changes to Markdown files
      - '.github/workflows/publish-markdown.yml'  # Also trigger on workflow changes
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated from v3

      - name: Setup Pages
        uses: actions/configure-pages@v4 # Updated from v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Updated to latest stable Ruby
          bundler-cache: true
          cache-version: 1 # To ensure cache invalidation when needed

      - name: Install Jekyll
        run: |
          gem install jekyll bundler
          bundle init
          bundle add jekyll --version "~>4.3.3" # Updated to latest Jekyll
          bundle add webrick
          bundle add jekyll-theme-cayman --version "~> 0.2.0"
          bundle add jekyll-relative-links --version "~> 0.7.0"

      - name: Create Jekyll configuration
        run: |
          cat > _config.yml << EOL
          title: GitHub/IBM POV Documents
          description: Technical point of view documents for GitHub and IBM
          theme: jekyll-theme-cayman
          markdown: kramdown
          kramdown:
            input: GFM
            syntax_highlighter: rouge
          plugins:
            - jekyll-relative-links
            - jekyll-seo-tag
          relative_links:
            enabled: true
            collections: true
          EOL

      - name: Create index page if it doesn't exist
        run: |
          if [ ! -f "index.md" ]; then
            cat > index.md << EOL
          ---
          layout: default
          title: GitHub/IBM POV Documents
          ---

          # GitHub/IBM POV Documents

          This site contains technical point of view documents for GitHub and IBM.

          ## Available Documents

          - [GitHub Organization Design (GI-POV-1)](gi-pov-1.html)
          - [Branching Strategies (GI-POV-2)](gi-pov-2.html)
          EOL
          fi

      - name: Ensure Markdown files have front matter
        run: |
          for file in *.md; do
            if [ "$file" != "index.md" ] && [ -f "$file" ]; then
              # Check if file already has front matter
              if ! grep -q "^---" "$file"; then
                # Add front matter to the beginning of the file
                tmp=$(mktemp)
                echo "---" > "$tmp"
                echo "layout: default" >> "$tmp"
                echo "title: $(basename "$file" .md)" >> "$tmp"
                echo "---" >> "$tmp"
                cat "$file" >> "$tmp"
                mv "$tmp" "$file"
                echo "Added front matter to $file"
              fi
            fi
          done

      - name: List all files before build
        run: ls -la

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --trace
          echo "Jekyll build completed"
          ls -la _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Updated from v2
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Updated from v2

      - name: Output Pages URL
        run: echo "Your site is published at ${{ steps.deployment.outputs.page_url }}"
